// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5IZz4iEYglFlaRf5lS6gP2C4FkvtTzI',
    appId: '1:390738255918:web:273a97bb0adf8a402a3fbf',
    messagingSenderId: '390738255918',
    projectId: 'flutter-planner-18484',
    authDomain: 'flutter-planner-18484.firebaseapp.com',
    storageBucket: 'flutter-planner-18484.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHk0gPlUmV5lzyIo9fhpvhHMNx7bEMb8',
    appId: '1:390738255918:android:10ede93c88da88c32a3fbf',
    messagingSenderId: '390738255918',
    projectId: 'flutter-planner-18484',
    storageBucket: 'flutter-planner-18484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF9PjRSooDdBsGKb6oHkF_Ia7TilDX-E0',
    appId: '1:390738255918:ios:edd5cbfa2d94d4392a3fbf',
    messagingSenderId: '390738255918',
    projectId: 'flutter-planner-18484',
    storageBucket: 'flutter-planner-18484.appspot.com',
    iosBundleId: 'com.example.flutterPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF9PjRSooDdBsGKb6oHkF_Ia7TilDX-E0',
    appId: '1:390738255918:ios:edd5cbfa2d94d4392a3fbf',
    messagingSenderId: '390738255918',
    projectId: 'flutter-planner-18484',
    storageBucket: 'flutter-planner-18484.appspot.com',
    iosBundleId: 'com.example.flutterPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ5IZz4iEYglFlaRf5lS6gP2C4FkvtTzI',
    appId: '1:390738255918:web:3ee2af8eeaea5db22a3fbf',
    messagingSenderId: '390738255918',
    projectId: 'flutter-planner-18484',
    authDomain: 'flutter-planner-18484.firebaseapp.com',
    storageBucket: 'flutter-planner-18484.appspot.com',
  );
}
